"""
report_generator.py
Generates downloadable Markdown, CSV, and HTML reports summarizing the
detected brute-force activity, statistics, and recommendations.
"""

from __future__ import annotations

import csv
import io
from datetime import datetime
from pathlib import Path
from typing import List

import constants
from analyzer import LogAnalyzer, Statistics
from detector import Alert
from logger import get_logger

logger = get_logger(__name__)


class ReportGenerator:
    """Builds Markdown, CSV, and HTML report content from analysis results."""

    def __init__(self, export_dir: str = constants.REPORTS_DIR) -> None:
        self.export_dir = Path(export_dir)
        self.export_dir.mkdir(parents=True, exist_ok=True)

    # ------------------------------------------------------------------
    # Markdown
    # ------------------------------------------------------------------
    def generate_markdown(self, stats: Statistics, alerts: List[Alert],
                           recommendations: List[str]) -> str:
        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        lines: List[str] = []
        lines.append("# Brute Force Attack Detection Report")
        lines.append(f"*Generated: {now}*\n")

        lines.append("## Executive Summary")
        lines.append(
            f"This report summarizes authentication log analysis covering "
            f"**{stats.total_entries}** log entries. A total of "
            f"**{stats.total_alerts}** alerts were generated, involving "
            f"**{stats.unique_attackers}** unique attacker IP(s) targeting "
            f"**{stats.unique_users_targeted}** unique account(s).\n"
        )

        lines.append("## Statistics")
        for key, value in stats.to_summary_dict().items():
            lines.append(f"- **{key}:** {value}")
        lines.append("")

        lines.append("## Severity Distribution")
        for sev, count in stats.severity_breakdown.items():
            lines.append(f"- **{sev}:** {count}")
        lines.append("")

        lines.append("## Detected Alerts")
        if alerts:
            lines.append("| Severity | Type | IP | User | Failed Attempts | Time | MITRE |")
            lines.append("|---|---|---|---|---|---|---|")
            for a in alerts:
                ts = a.timestamp.strftime("%Y-%m-%d %H:%M:%S") if a.timestamp else "N/A"
                mitre = f"{a.mitre_id} {a.mitre_name}".strip()
                lines.append(
                    f"| {a.severity} | {a.alert_type} | {a.ip} | {a.username} | "
                    f"{a.failed_attempts} | {ts} | {mitre} |"
                )
        else:
            lines.append("No alerts were generated for this dataset.")
        lines.append("")

        lines.append("## Top Attacker IPs")
        for ip, count in stats.top_attacker_ips:
            lines.append(f"- {ip}: {count} failed attempts")
        lines.append("")

        lines.append("## Top Targeted Users")
        for user, count in stats.top_targeted_users:
            lines.append(f"- {user}: {count} failed attempts")
        lines.append("")

        lines.append("## Recommendations")
        for rec in recommendations:
            lines.append(f"- {rec}")
        lines.append("")

        lines.append("---")
        lines.append("*Report generated by Brute Force Attack Detector*")

        return "\n".join(lines)

    # ------------------------------------------------------------------
    # CSV
    # ------------------------------------------------------------------
    def generate_csv(self, alerts: List[Alert]) -> str:
        buffer = io.StringIO()
        fieldnames = [
            "Alert Type", "Severity", "Attacker IP", "Target User",
            "Failed Attempts", "Timestamp", "Description", "MITRE Technique",
            "Risk Score", "Confidence", "Service",
        ]
        writer = csv.DictWriter(buffer, fieldnames=fieldnames)
        writer.writeheader()
        for alert in alerts:
            writer.writerow(alert.to_dict())
        return buffer.getvalue()

    # ------------------------------------------------------------------
    # HTML
    # ------------------------------------------------------------------
    def generate_html(self, stats: Statistics, alerts: List[Alert],
                       recommendations: List[str]) -> str:
        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        rows = ""
        for a in alerts:
            ts = a.timestamp.strftime("%Y-%m-%d %H:%M:%S") if a.timestamp else "N/A"
            color = constants.SEVERITY_COLORS.get(a.severity, "#888")
            rows += (
                f"<tr><td><span style='background:{color};color:white;"
                f"padding:2px 8px;border-radius:4px;'>{a.severity}</span></td>"
                f"<td>{a.alert_type}</td><td>{a.ip}</td><td>{a.username}</td>"
                f"<td>{a.failed_attempts}</td><td>{ts}</td>"
                f"<td>{a.mitre_id} {a.mitre_name}</td></tr>\n"
            )

        stats_rows = "".join(
            f"<tr><td>{k}</td><td>{v}</td></tr>\n"
            for k, v in stats.to_summary_dict().items()
        )
        rec_items = "".join(f"<li>{r}</li>\n" for r in recommendations)

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Brute Force Attack Detection Report</title>
<style>
  body {{ font-family: 'Segoe UI', Arial, sans-serif; background:#0f172a; color:#e2e8f0; margin:0; padding:2rem; }}
  h1 {{ color:#f97316; }}
  h2 {{ color:#38bdf8; border-bottom:1px solid #334155; padding-bottom:4px; margin-top:2rem;}}
  table {{ width:100%; border-collapse:collapse; margin-top:1rem; }}
  th, td {{ text-align:left; padding:8px 10px; border-bottom:1px solid #334155; }}
  th {{ background:#1e293b; }}
  tr:hover {{ background:#1e293b; }}
  .summary {{ background:#1e293b; padding:1rem 1.5rem; border-radius:8px; }}
  footer {{ margin-top:2rem; color:#64748b; font-size:0.85rem; }}
</style>
</head>
<body>
  <h1>🛡️ Brute Force Attack Detection Report</h1>
  <p><em>Generated: {now}</em></p>

  <h2>Executive Summary</h2>
  <div class="summary">
    <p>This report summarizes authentication log analysis covering
    <strong>{stats.total_entries}</strong> log entries. A total of
    <strong>{stats.total_alerts}</strong> alerts were generated, involving
    <strong>{stats.unique_attackers}</strong> unique attacker IP(s) targeting
    <strong>{stats.unique_users_targeted}</strong> unique account(s).</p>
  </div>

  <h2>Statistics</h2>
  <table><tr><th>Metric</th><th>Value</th></tr>{stats_rows}</table>

  <h2>Detected Alerts</h2>
  <table>
    <tr><th>Severity</th><th>Type</th><th>IP</th><th>User</th>
        <th>Failed Attempts</th><th>Time</th><th>MITRE</th></tr>
    {rows if rows else "<tr><td colspan='7'>No alerts generated</td></tr>"}
  </table>

  <h2>Recommendations</h2>
  <ul>{rec_items}</ul>

  <footer>Report generated by Brute Force Attack Detector v1.0.0</footer>
</body>
</html>"""
        return html

    # ------------------------------------------------------------------
    # File persistence
    # ------------------------------------------------------------------
    def save_report(self, content: str, filename: str) -> Path:
        path = self.export_dir / filename
        path.write_text(content, encoding="utf-8")
        logger.info("Saved report to %s", path)
        return path
